language: ruby
rvm:
- 2.3.1
before_install:
    - gem update --system
    - gem install bundler


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  on:
    branch: master
