---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: collections/_posts/fr
  label: French - posts
  create: all
  match: "**/*"
  new_doc_ext: ".md"
- type: directory
  path: collections/_posts/en
  label: English - post
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - welcome
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
