---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: collections/_people/fr
  label: French - people
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_people/en
  label: English - people
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_projects/fr
  label: French - projects
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_projects/en
  label: English - projects
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_posts/fr
  label: French - posts
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - welcome-a32ce249-547c-4444-b033-0b5a74daaf09
- type: directory
  path: collections/_posts/en
  label: English - post
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - welcome
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
