---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: collections/_people/fr
  label: People (FR)
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_people/en
  label: People (EN)
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_projects/fr
  label: French - projects
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_projects/en
  label: English - projects
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_publications/fr
  label: French - publications
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_publications/en
  label: English - publications
  create: all
  match: "**/*"
  new_doc_ext: md
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
