---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts ERPI
  create: documents
  new_doc_ext: '20190411151321'
  templates:
  - template-post
- type: directory
  path: collections/_people/fr
  label: French - people
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_people/en
  label: English - people
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_projects/fr
  label: French - projects
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - lorraine-smart-city-living-lab-f4befa28-bdf1-4daa-a16a-977895ccc509
- type: directory
  path: collections/_projects/en
  label: English - projects
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - lorraine-smart-city-living-lab-f4befa28-bdf1-4daa-a16a-977895ccc509
- type: directory
  path: collections/_posts/fr
  label: French - posts
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - template-post
- type: directory
  path: collections/_posts/en
  label: English - post
  create: all
  match: "**/*"
  new_doc_ext: ":year:-:month:-:day:-:filename:.md"
  templates:
  - template-post
- type: directory
  path: collections/_publications/fr
  label: French - publications
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_publications/en
  label: English - publications
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - welcome
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
